name: search-ssl
channels:
  - conda-forge
  - bioconda
dependencies:
  - lightning
  - snakemake
  - sunpy
  - pandas
  - wandb
  - ipywidgets
  - opencv
  - pip
  - pip:  
    - lightly
    - git+https://github.com/hits-sdo/hits-sdo-packager.git@pip_nodata
