name: search-ssl
channels:
  - pytorch
  - conda-forge
  - nvidia
  - rapidsai
  - bioconda
dependencies:
  - python=3.10
  - snakemake-minimal
  - wandb
  - ipywidgets
  - umap-learn
  - opencv
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - scikit-learn=1.2.2
  - plotly
  - cuml
  - pip
  - pip:
    - lightning
    - lightly
    - sunpy
    - pandas
    - wandb
    - matplotlib
    - hdbscan
    - umap-learn
    - seaborn
    - git+https://github.com/hits-sdo/hits-sdo-packager.git@pip_nodata

