name: search-ssl
channels:
  - pytorch
  - conda-forge
  - nvidia
  - rapidsai
  - bioconda
dependencies:
  - python=3.10
  - snakemake
  - wandb
  - ipywidgets
  - umap-learn
  - opencv
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=11.8
  - scikit-learn=1.2.2
  - plotly
  - cuml
  - sunpy
  - pandas
  - hdbscan
  - wandb
  - matplotlib
  - seaborn
  - pip
  - pip:
    - streamlit
    - lightning
    - lightly
    - git+https://github.com/hits-sdo/hits-sdo-packager.git@pip_nodata
    - git+https://github.com/hits-sdo/streamlit-cropper.git
