data:
  augmentation: double
  data_path: data/tiles_HMI_small
meta:
  project: solar-self-similarity
  name: nxtent-loss
  group: debug
  tags: []
  resume: false
  outdir: ''
model:
  checkpoint_location: None
  dropout_ratio: 0
  load_checkpoint: false
  projection_size: 2
  prediction_size: 2
  channels: 1
testing:
  eval: false
training:
  batch_size: 256
  epochs: 30
  lr: 0.01
  wd: 0.0001
  momentum_start: 0.99
  momentum_end: 1
  loss: 'contrast'